- name: Migrate VMware VM to OpenShift Virtualization using MTV
  hosts: localhost
  gather_facts: no
  vars:
    mtv_namespace: "vm-migration"  # MTV project namespace in OpenShift
    migration_plan_name: "vmware-to-openshift-migration"
    provider_name: "vmware"
    provider_type: "vsphere"
    target_namespace: "vm-migration"
    vmware_vm_name: "application02"
  tasks:  
    - name: Create a migration plan in MTV
      kubernetes.core.k8s:
        api_version: forklift.konveyor.io/v1beta1
        kind: Plan
        metadata:
          name: "{{ migration_plan_name }}"
          namespace: "{{ mtv_namespace }}"
        spec:
          targetNamespace: "{{ target_namespace }}"
          provider:
            source:
              name: "{{ provider_name }}"
              namespace: "{{ mtv_namespace }}"
            destination:
              name: "openshift"
              namespace: "{{ mtv_namespace }}"
          vms:
            - name: "{{ vmware_vm_name }}"
    - name: Start the migration plan
      kubernetes.core.k8s:
        api_version: forklift.konveyor.io/v1beta1
        kind: Migration
        metadata:
          generateName: "{{ migration_plan_name }}-"
          namespace: "{{ mtv_namespace }}"
        spec:
          plan:
            name: "{{ migration_plan_name }}"
            namespace: "{{ mtv_namespace }}"
 
    - name: Monitor the migration process
      kubernetes.core.k8s_info:
        api_version: forklift.konveyor.io/v1beta1
        kind: Migration
        namespace: "{{ mtv_namespace }}"
      retries: 10
      delay: 60
      until: "{{ migration.status.conditions | selectattr('type', 'equalto', 'Succeeded') | first | attr('status') == 'True' }}"
    - name: Ensure the VM is running in OpenShift Virtualization
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vmware_vm_name }}"
        namespace: "{{ target_namespace }}"
      register: migrated_vm
 
    - name: Start the VM in OpenShift if not running
      kubernetes.core.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vmware_vm_name }}"
        namespace: "{{ target_namespace }}"
        state: started
      when: not migrated_vm.resources[0].status.ready
