- name: Migrate multiple VMs from VMware to OpenShift Virtualization
  hosts: localhost
  gather_facts: no
  vars:
    project_name: vm-migration
    vm_names:
      - Application01
      - Application02
      - cp-open5gs
    migration_plan_name: vmware-to-ocp-100
    source_provider_name: vmware
    target_provider_name: ocp-virt
    vmware_datacenter: Datacenter
    vmware_cluster: Cluster1
    target_namespace: vm-migration
    openshift_api_url: https://api.ibmcoe.techmapps.local:6443
    openshift_token: sha256~qdUBdeRmjZBDAixzxILHH-U8J3UJ945CKz75HCvnSf8
    networkmap_name: networkmap-001
    storagemap_name: storagemap-001
  tasks:
    - name: Create MTV Migration Plan
      uri:
        url: "{{ openshift_api_url }}/apis/forklift.konveyor.io/v1beta1/namespaces/{{project_name }}/migrationplans"
        method: POST
        headers:
          Authorization: Bearer {{ openshift_token }}
          Content-Type: application/json
        body_format: json
        body:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: MigrationPlan
          metadata:
            name: "{{ migration_plan_name }}"
            namespace: "{{ project_name }}"
          spec:
            provider:
              source: "{{ source_provider_name }}"
              destination: "{{ target_provider_name }}"
            targetNamespace: "{{ project_name }}"
            vms:
              - name: "{{ item }}"
                sourceProvider: "{{ source_provider_name }}"
            map:
              network: "{{ networkmap_name }}"
              storage: "{{ storagemap_name }}"
        status_code: 201
      loop: "{{ vm_names }}"
      register: migration_plan
    - name: Check Migration Plan Creation Status
      debug:
        msg: "Migration Plan Creation Status: {{ migration_plan.json }}"
    - name: Start Migration Plan Execution
      uri:
        url: "{{ openshift_api_url }}/apis/forklift.konveyor.io/v1beta1/namespaces/{{project_name }}/migrationplans/{{ migration_plan_name }}/migrate"
        method: POST
        headers:
          Authorization: Bearer {{ openshift_token }}
          Content-Type: application/json
        body_format: json
        body: {}
        status_code: 202
      register: start_migration
    - name: Check Migration Execution Status
      uri:
        url: "{{ openshift_api_url }}/apis/forklift.konveyor.io/v1beta1/namespaces/{{project_name }}/migrationplans/{{ migration_plan_name }}"
        method: GET
        headers:
          Authorization: Bearer {{ openshift_token }}
        status_code: 200
      register: migration_status
    - name: Display Migration Plan Status
      debug:
        msg: "Migration Status: {{ migration_status.json.status }}"
